#!/usr/bin/python
# -*- coding: utf-8 -*-
__author__ = 'Jernej Makovšek <jernej.makovsek@gmail.com>'

"""
Gets historic trade data from bitcoincharts.com, normalizes and saves it.

Downloads historic market data for all available markets from bitcoincharts.com, normalizes it relative to USD
and saves it. There are however limitations with bitcoincharts.com: trade data is not
available at full resolution and is delayed by approx. 15 minutes.
"""
from lib import constants, io, logger as log, database

logger = log.get_custom_logger(__file__, constants.log.LEVEL)


if __name__ == "__main__":
    try:
        database.create_database(constants.db.PATH)

        database_files = io.list_files(constants.db.PATH)

        # normalize and order the database
        normalized_database = database.get_normalized_ordered_data(database_files)

        io.serialize_data(
            path=constants.db.PATH + constants.db.NORMALIZED_FILE_NAME,
            data=normalized_database
        )
    except Exception as e:
        logger.exception(e)
        print e.message
