#!/usr/bin/python
# -*- coding: utf-8 -*-
__author__ = 'Jernej Makovšek <jernej.makovsek@gmail.com>'

"""
Simulate how agents respond to price changes.

Details:
Ideas based on thermodynamic are used to model agent behaviour. Note that since we deal with limited information
significant error is expected but it should converge with time: error[t1] > error[t2] (based on information
completeness axiom).
"""
from lib import logger as log, constants, io, agents

logger = log.get_custom_logger(__file__, constants.log.LEVEL)


if __name__ == "__main__":
    try:
        database, path = io.loadUserSpecifiedDatabase()

        agents_greed = float(raw_input("Set greed of simulated agents (0.0 - 0.9): "))

        # get simulation results
        response_data = agents.getAgentReactions(database, agents_greed)

        results_file_name = path + "_simulated_response_" + "with_parameter_" + str(agents_greed) + ".json"

        # save simulated results
        io.serialize_data(results_file_name, response_data)
    except Exception as e:
        logger.exception(e)
        print e.message
